[[scrambling]]
=== Scrambling

A probabilistic alternative to temporal and spatial partitioning is to scramble microarchitectural state.
Using the cache memory example, and assuming a set-associative cache, the covert channel danger is that the spy can determine if a cache line has been accessed by the trojan and in which set it is located.
The designer can "scramble" the selected set with a keyed pseudorandom function applied to the _set selector bits_ of the address.
If the security domain changes, the key is changed as well, making all the cache line entries obsolete.
If execution returns to the initial security domain, the initial key is reestablished and old entries become valid again.
It is still necessary to modify the cache behavior to account for the scrambling: for example, a collision (same tag, same set) with a different key should not assume that it is the same cache line.

The probabilistic nature of this countermeasure does not provide the same security guarantee as temporal and spatial partitioning; however, it is expected to have low overhead.
