[[timing_fence]]
=== Timing fence

A difficulty with partitioning is identifying security domain switches.
There is no explicit definition of security domains in the RISC-V ISA.
Yet there are implicit ones : privilege levels, address space identifiers (ASID), virtual machine identifiers (VMID), supervisor domain identifiers (SDID), ...
It is possible to have the microarchitecture adapt to these implicit domain switches, implementing partitioning with respect to them.

But *separation of concerns* is necessary, the ASID value has not been designed as a security feature, but as an optimization.
The attackers could meddle with the value, searching for collisions by spawning lots of processes for example, to control partitioning.

**To be updated** A current RISC-V extension proposal introduces the `fence.time` timing fence, with the following semantics:

[NOTE]
.fence.time semantics
====
The timing of any instruction or sequence of instructions that execute after FENCE.TIME must be independent of any sequence of instructions before the fence, or equivalently independent of the microarchitectural state before the fence.
====

In other words, the timing fence is an instruction that signals to the microarchitecture when partitioning is necessary.


