[[covert-side-channels]]
=== Covert and Side Channels

The ability of an attacker to exfiltrate and retrieve a secret can be viewed as the establishment of a communication channel.
The attacker’s goal is to establish this communication channel across a security boundary.

For example, this could allow a user-mode process to read a secret manipulated during a system call executed in supervisor mode.

Like any communication channel, there is an emitter (often called the Trojan) trying to communicate the secret to the receiver (often called the Spy).
Two threat models are usually considered:

* *Covert Channels* refer to the communication channels where both the Trojan and Spy are controlled by the attacker.
* *Side Channels* refer to communication channels where only the Spy is under the attacker's control. In this model, the Trojan's role is inadvertently played by the victim.

These communication channels can take several forms.
A secret can be communicated, or leaked, as secret-dependent power consumption measured with an oscilloscope.
Or a function's duration may depend on secret data; in this case, the channel is a timing (covert or side) channel.

Looking at timing channels in a CPU, two main causes can be found.

* *Architectural timing channels* occur when different execution paths are followed depending on the secret, for example, by branching on a condition involving a secret value. Different execution paths usually mean different execution duration. Architectural timing channels are software vulnerabilities: they should not occur in security-minded programs.
* *Microarchitectural timing channels* can occur even in the absence of architectural timing channels, with a correct software implementation. In this case, timing variation can still occur due to the hardware implementation. For example, a _load_ instruction whose address is secret-dependent can induce a covert channel because of cache memories.

// constant time programming
[NOTE]
.Constant time programming
====
Constant time programming consists in making sure that execution duration is constant time, and thus independent of secrets.
It encompasses the set of techniques (programming patterns, compiler configurations, ...) to achieve said result.
Beware, depending on the context, constant time programming may only consider architectural timing channels and declare microarchitectural leakage out of scope.
====

Microarchitectural timing channels are caused by microarchitectural structures (buffers, finite state machines, ...) necessary to improve the performance of the microarchitecture. Timing variation is there on purpose: for example, cache memories introduce timing variability between hit and miss entries to optimize repetitive memory accesses.
As such, microarchitectural timing channels are not due to hardware implementation error per se, but rather to misusing this implementation. Hardware techniques to limit covert channels are discussed in <<mitigating-covert-channels>>.

*Any microarchitectural state that depends on execution history and impacts timing can be used to implement a covert channel.*
This includes cache memories, branch predictors, other kinds of buffers (TLBs, fetch buffers, trace buffers, ...), even finite state machines.

// Example FLUSH+RELOAD ?
